#ifndef LIBSERSI_UTILS_PDUTYPE_H_
#define LIBSERSI_UTILS_PDUTYPE_H_

namespace dis {
enum PduType {
  kOther = 0,
  kEntityState = 1,
  kFire = 2,
  kDetonation = 3,
  kCollision = 4,
  kServiceRequest = 5,
  kResupplyOffer = 6,
  kResupplyReceived = 7,
  kResupplyCancel = 8,
  kRepairComplete = 9,
  kRepairResponse = 10,
  kCreateEntity = 11,
  kRemoveEntity = 12,
  kStartResume = 13,
  kStopFreeze = 14,
  kAcknowledge = 15,
  kActionRequest = 16,
  kActionResponse = 17,
  kDataQuery = 18,
  kSetData = 19,
  kData = 20,
  kEventReport = 21,
  kComment = 22,
  kElectronicEmmisions = 23,
  kDesignator = 24,
  kTransmitter = 25,
  kSignal = 26,
  kReceiver = 27,
  kIff = 28,
  kUnderwaterAcoustic = 29,
  kSupplementalEmissionEntity = 30,
  kIntercomSignal = 31,
  kIntercomControl = 32,
  kAggregateState = 33,
  kIsGroupOf = 34,
  kTransferOwnership = 35,
  kIsPartOf = 36,
  kMinefieldState = 37,
  kMinefieldQuery = 38,
  kMinefieldData = 39,
  kMinefieldResponseNack = 40,
  kEnvironmentalProcess = 41,
  kGriddedData = 42,
  kPointObjectState = 43,
  kLinearObjectState = 44,
  kArealObjectState = 45,
  kTspi = 46,
  kAppearance = 47,
  kArticulatedParts = 48
};
}

#endif  // LIBSERSI_UTILS_PDUTYPE_H_
